name: Continuous Integration

on: [push]

jobs:
  buildAndTest:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build Images
        run: . ./build_images.sh

      - name: Run Cluster
        run: . ./build_script
