FROM centos:7

RUN \
  yum update -y && \
  yum install -y epel-release && \
  yum install -y rabbitmq-server && \
  rabbitmq-plugins enable rabbitmq_management && \
  yum clean all

COPY bootstrap.sh rabbitmq.config /
EXPOSE 5671 5672 15671 15672 25672
ENTRYPOINT ["sh","/bootstrap.sh"]
