name: Continuous Integration

on: [push]

jobs:
  buildAndTest:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: List file
        run: pwd && ls -l
      - name: Build Images
        run: . ./build_images.sh
      - name: Run Cluster
        run: . ./build_script.sh
      - name: Verify
        run: docker logs sender && docker logs receiver
