name: Continuous Integration

on: [push]

jobs:
  buildAndTest:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: List file
        run: pwd && ls -l
      - name: Build Images
        run: bash rabbitmq_cluster/build_images.sh
      - name: Run Cluster
        run: bash rabbitmq_cluster/build_script
